backports: port S16_* backport frmo master [CORE18 ONLY]
We merged a backport change in master but can't cherry-pick
it in Core18. Port the fix manually to Core18.

This fixes:
drivers/net/wireless/intel/iwlwifi/mvm/tt.c:521:39: error: 'S16_MIN' undeclared (first use in this function)
   if (mvm->tz_device.temp_trips[i] != S16_MIN) {

type=maint

Change-Id: Ia3404f974c4c19d9ae6fd98393b8d030c68e0a54
Signed-off-by: Emmanuel Grumbach <emmanuel.grumbach@intel.com>
Reviewed-on: https://git-amr-3.devtools.intel.com/gerrit/21179
Reviewed-by: Coelho, Luciano <luciano.coelho@intel.com>
Reviewed-by: Mordechai, Dan <dan.mordechai@intel.com>
Tested-by: ec ger unix iil jenkins <EC.GER.UNIX.IIL.JENKINS@INTEL.COM>
x-iwlwifi-stack-dev: 13e4fe028cfec7b5b8b47bdbad0127a12abffd7f